### ISSUE TITLE
API 의논 사항

### ISSUE THREAD

**Issue by dev-Lena** [codesquad-member-2020/airbnb-05#1]
API와 관련하여 의견이나 궁금한 점있으면 남겨주세요!

**Comment by dev-Lena** [comment]
### 2020.05.18
> 내일 스크럼에서 의논해볼 사항들
#### 메인 화면 의논해볼 사항들
1. 어느 나라를 기준으로 할건지, 어느 도시가 있는지
2. 필터링 조건(날짜, 인원, 가격) 중 가격 설정에서 평균 가격은 누가 계산할지
3. 필터링 조건 - null 가능하게 할 수 있는지 (모든 조건이 충족되지 않아도 필터링 가능)
4. 별점 만점 기준(5/10/100)
5. 즐겨찾기
6. 달러 -> 원
7. 가격 필터링  가격 범위(그래핑 기준)

**Comment by suhyunsim** [comment]
* DB에 저장할 데이터 출처
http://insideairbnb.com/get-the-data.html

**Comment by Limwin94** [comment]
3번은 협의가 된 사항입니다.
모든 조건(가격, 인원 수, 기간)이 충족되지 않아도 서버와 통신 가능

**Comment by suhyunsim** [comment]
함께 선정할 데이터 항목 정리했습니다.
추가할 항목을 표시해주세요!
[스프레드 시트](https://docs.google.com/spreadsheets/d/1yfaYt5F1RaKIgYqBssW1TQwBCWqHktuFrzmOjOXk22U/edit?usp=sharing)

**Comment by suhyunsim** [comment]
## 결정 사항
* 어느 나라를 기준으로 할건지, 어느 도시가 있는지
> 미국, 약 20개 도시 예상, 한 도시 당 50개 정도의 데이터, 총 1000개
> map 활용도를 높이기 위해 한 국가의 여러 도시를 활용할 예정입니다.
<br>

* 필터링 조건(날짜, 인원, 가격) 중 가격 설정에서 평균 가격은 누가 계산할지
> 🍇🦾
<br>

* 별점 만점 기준(5/10/100)
> 100점 점수를 기준으로 20으로 나눈 값 (5점 만점의 데이터)
<br>

* 즐겨찾기
> 로그인한 유저마다 다른 favorites 제공
> 서버에서 관리
<br>

* 통화 $ -> ₩
> 서버에서 달러 가격으로 제공
> 할인가 제공하지 않거나 일률적인 할인율 ## 결정 사항
<br>

* 가격 필터링 가격 범위(그래핑 기준)
> 가격 전체 리스트 (최저가 ~ 최고가) 정렬 후 제공

**Comment by suhyunsim** [comment]
* 도시 목록
```
Asheville, North Carolina, United States
Austin, Texas, United States
Boston, Massachusetts, United States
Cambridge, Massachusetts, United States
Chicago, Illinois, United States
New Orleans, Louisiana, United States
New York City, New York, United States
Oakland, California, United States
Portland, Oregon, United States
San Francisco, California, United States
Santa Cruz County, California, United States
Seattle, Washington, United States
```

12개 도시
3435개 데이터

**Comment by dev-Lena** [comment]
감사합니다! 오늘도 고생많이하셨어요 우리 백엔드 @suhyunsim  🐥🌻

**Comment by dev-Lena** [comment]
### 2020.05.20 의논 사항
> iOS 에서 확인할 사항
https://docs.google.com/spreadsheets/d/1yfaYt5F1RaKIgYqBssW1TQwBCWqHktuFrzmOjOXk22U/edit#gid=0

-> 이 중 추가적으로 고려할 사항
1. 정상가, 할인가
2. 수수료/ 세금
3. 예약 신청시 인원수*일박당 요금*숙박일수를 계산한 총 금액 합계

**Comment by dev-Lena** [comment]
### 2020.05.20 결정사항
1. 위 함께 선정할 데이터 항목 스프레드 시트 중 'amenities' 필드 추가 부탁드립니다!
2. 수수료/세금 필드도 추가 부탁드립니다!
3. 예약 확인 화면 - 인원수 *일박당요금*숙박일수를 계산한 총 금액 합계 등의 계산 로직은 백엔드에서...(?!)
<- 혹시 의논했던 것고 다른 부분이 있으면 코멘트 달아주세요!

**Comment by suhyunsim** [comment]
# 2020.05.20 API 문서 ver.1

* [ver.1](https://github.com/codesquad-member-2020/airbnb-05/wiki/API-%EB%AC%B8%EC%84%9C-ver.1)
* 버전이 추가될 때마다 위키 페이지에 업데이트 하겠습니다.
* 페이지 상단과 이슈 코멘트로 변경 사항을 함께 명시할게요!

## 논의할 사항
- [ ] 도시 선택 후 스크롤 내릴 때마다 오는 요청에 대한 궁금점 (infinity scroll)
- [x] 로그인 정보를 cookie로 관리할 것인지
- [x] 가격에 대한 정보(환율 반영한 원화로 전달할 것인지)
- [x] 가격에 대한 정보(정가 -> 할인가, 일률적인 할인율 or 랜덤, 확장성에 대한 논의)
- [x] 가격에 대한 정보(cleaning_fee, service_fee 0 가능)
- [x] 가격에 대한 정보(ocupation_taxes_and_fee)
- [x] 가격에 대한 정보(total_fee) 계산해서 줄 것인지
- [x] 가격 필터링 탭 클릭 시 요청에 대한 논의 (min, max 고정 / 평균가격: 필터링 조건에 따른 값)
- [x] 즐겨찾기와 예약 요청의 restful api url
- [x] patch, post, delete 요청에 대한 응답
- [ ] 예약 완료 후 조회 페이지: 예약한 숙소 전체 데이터인지?
- [x] 체크인, 체크아웃 한 날짜를 기준으로 몇 박을 숙박하는지 서버에서 계산해서 전달 or 앞에서 계산
- [ ] 지도 api

**Comment by suhyunsim** [comment]
# 2020.06.03 API 문서 ver.2

* [ver.2](https://github.com/codesquad-member-2020/airbnb-05/wiki/API-%EB%AC%B8%EC%84%9C-ver.2)

* guestId=1 넣어주기...❤️

**Comment by suhyunsim** [comment]
# 2020.06.04 api ver.3
* [ver.3](https://github.com/codesquad-member-2020/airbnb-05/wiki/API-%EB%AC%B8%EC%84%9C-ver.3)
* oauth 적용

**Comment by dev-Lena** [comment]
데모끝 !!! 같은 조로 함께할 수 있어서 너무 영광이었습니다 다들 감사합니다!! 🥳🎉🌻 🌝
