### ISSUE TITLE
[iOS] 메인화면 filter view(인원 설정) 구성

### ISSUE THREAD

**Issue by Limwin94** [codesquad-member-2020/airbnb-05#14]
* filter view들 (가격, 인원, 날짜)의 header view, footer view는 재사용이 가능함.

#### Header View
- [x] header view XIB 생성
- [x] header view class와 XIB 연결
- [x] VC와 연결

#### Footer View
- [x] header view XIB 생성
- [x] header view class와 XIB 연결
- [x] VC와 연결

#### 인원 선택 View
* vertical stack view로 넣고, Inspectable을 넣어서 title(성인, 청소년, 유아), subtitle(설명)을 storyboard에서 변경할 수 있도록 함.
- [x]  재사용으로 인한 XIB 생성
- [x] 초기화 버튼 동작

### 디자인
- [x] 모달 뷰 dim 처리
- [x] 모달 뷰 corner radius 처리
- [x] 완료버튼 corner radius 처리
- [x] 완료버튼 클릭시 background color pink로 변경 < - > gray 로 변경

**Comment by Limwin94** [comment]
@dev-Lena 
세부 디자인은 나중에 조정하는 걸로 하겠습니다.

**Comment by dev-Lena** [comment]
> @dev-Lena
> 세부 디자인은 나중에 조정하는 걸로 하겠습니다.

메인화면 완성 후 세부 디자인 적용하도록 하죠!
