### ISSUE TITLE
[iOS - Pair] 캘린더 구현

### ISSUE THREAD

**Issue by dev-Lena** [codesquad-member-2020/airbnb-05#21]
### 구현 요구사항
1. CollectionView를 사용한 캘린더 모양 구현
2. Calendar 클래스를 이용한 날짜 표시
3. 2 개의 셀 선택 가능
4. 셀 선택 해제 가능
5. 체크인 / 체크아웃 시 고려할 사항
  > 먼저 날짜: 더 이른 날짜 ex) 16일
  > 나중 날짜: 더 나중 날짜 ex) 19일
  5.1. 먼저 날짜가 체크인 나중 날짜가 체크아웃일 경우
  5.2. 나중 날짜가 먼저 눌리고 먼저 날짜가 다음으로 눌린 경우
  5.3. 체크인 체크아웃의 날짜의 달이 바뀌는 경우
  5.4. 체크인 체크아웃을 선택한 후 체크 아웃 날짜를 선택 해지한 경우, 그리고 다시 다른 나중 날짜를 고른 경우
  5.5. 다음달로 넘어갈 때 넘어가는 방법: 스크롤 또는 페이지 등
  등등 🤯🤯🤯🤯🤯🤯

### 이 외에 기타 고려할 점이나 의논 사항은 코멘트로 남겨주세요!

**Comment by dev-Lena** [comment]
@Limwin94 
캘린더 동작 방법은 Airbnb 앱을 기준으로 참고하는건 어떤가요?

**Comment by Limwin94** [comment]
@dev-Lena 
한번 다운받아서 사용해보도록 하겠습니다.

**Comment by Limwin94** [comment]
05.25 진행사항

## 페어로 진행할 이슈
1. 달력 collection view 설정(달력 날짜 관련, 선택된 체크인-체크아웃 날짜 관리)하는 로직을 관리하는 객체 만들기

## Lin
1. 달력 날짜 이슈 해결.

## Lena
1. 즐겨찾기 버튼 view를 관리하는 객체 구현.
2. cell 선택 기능 구현 (체크인 - 체크아웃)
