### ISSUE TITLE
[iOS] 의논 사항

### ISSUE THREAD

**Issue by dev-Lena** [codesquad-member-2020/airbnb-05#5]
의논할 사항 및 궁금한 점 및 아이디어 등을 자유롭게 코멘트로 남겨주세요!

**Comment by dev-Lena** [comment]
### 지금까지 협의한 내용
1. 로그인 후 메인화면에 들어오기 전에 국가/도시를 선택한다. 메인 화면에서 선택한 도시의 숙소가 보여진다. (기간, 인원수, 가격 조건 미설정)
2. OAuth 로그인은 모든 화면을 만든 다음에 구현하기로 한다.
### 궁금한 점
1. 처음 메인화면에서 숙소를 표시할 때 네트워크에 요청해서 받아온 전체 데이터를 표시할 건지 아니면 10개나 15개 등 특정 단위로 받고 스크롤이 다 내려갔을 때 추가로 데이터를 받아 표시할지??
2. 이미지 캐싱을 이번에 구현할 건지

**Comment by dev-Lena** [comment]
### 궁금한 점에 대해 협의한 내용
1. 처음에 15개씩 받아오고 스크롤이 마지막까지 내려갔을 때 인디케이터가 보이고 다음 15개 숙소 정보를 네트워크에 요청해 받아온 후 받아온 15개의 숙소를 추가적으로 표시하기로 함.
-> 네트워크 요청시 받아오는 첫번째 인덱스 정보를 담아서 요청.
2. 메인화면 이미지 캐싱, 상세페이지 이미지 캐싱 구현하기로 함.

**Comment by dev-Lena** [comment]
* 맵 플로팅 버튼 사용?
[Floaty](https://github.com/kciter/Floaty)
* 메인화면 이미지 빠르게 스크롤 할 경우 페이지 컨트롤의 페이지와 일치하지 않는 이슈

**Comment by dev-Lena** [comment]
### JK에게 리뷰 요청한 PR

[iOS] 메인 화면 + 인원수 필터링 화면 + 캘린더 뼈대 화면 구현 #31

**Comment by dev-Lena** [comment]
## UIView @IBInspectable
### Border
1. borderWidth
2. borderColor
### Shadow
3. shadowOpacity
4. shadowOffset
5. shadowColor
6. shadowRadius
7. shadowRadius
### cornerRadius
8. cornerRadius

**Comment by Limwin94** [comment]
지금 button 클릭시에 어떤 view의 버튼이 클릭되었는지 로직을 짜는 중인데,
이러면 button의 superview의 superview의 superview로 가야지 어떤 view인지 나오는데 이 방법밖에 없을까?

![image](https://user-images.githubusercontent.com/49548908/82643827-32fad100-9c4b-11ea-9792-27e68abc5862.png)

**Comment by dev-Lena** [comment]
view 에서 GuestFilterViewController로 노티피케이션 보내는건 어떨까요??

**Comment by dev-Lena** [comment]
### 코딩 컨벤션
> 순서 : 프로퍼티 -> init 메소드 -> 메소드(IBAction 포함)
> 프로퍼티 순서 : IBOutlet -> static -> private -> public
> 클래스 이름과 프로퍼티 사이 한 줄 공백
> extension은 줄 띄움 없음 
>클래스 } 닫기 전에 마지막 줄 띄움 없음

**Comment by dev-Lena** [comment]
### 메인 화면 - 가격 필터 화면

[BezierPath를 이용한 곡선 그래프 예제 코드](https://gist.github.com/dev-Lena/12f71d8af107ec3ccf1fa0079f6cd8e0)입니다!

주말동안 이해하고 다음주 월요일에 서로 이해한 내용에 대해서 얘기 나눠봅시다!

[예제 링크 출처](https://stackoverflow.com/questions/13719143/draw-graph-curves-with-uibezierpath)

**Comment by dev-Lena** [comment]
데모날까지 마지막주도 화이팅입니다!
[iOS] 마지막주(3주) 스케쥴 #52

**Comment by dev-Lena** [comment]
## Map API 선택 관련 자료 링크입니다
[Apple Map vs Google Map 비교 자료 링크](https://www.digitaltrends.com/mobile/apple-maps-vs-google-maps/)

### @dev-Lena  @Limwin94  : Airbnb 앱의 숙소 기준이 미국이기 때문에 네이버 지도, 카카오 지도는 옵션에서 제외했습니다!

**Comment by dev-Lena** [comment]
데모 끝!!🌻
