### ISSUE TITLE
[iOS - Pair] 0603-0605 메인화면 네트워크 연결 + 이미지캐싱

### ISSUE THREAD

**Issue by dev-Lena** [codesquad-member-2020/airbnb-05#56]
### NetworkManager 객체
* [x] Swift Package Manager
* [x] Alamofire 라이브러리 사용

### UseCase 객체
* [x] Json Decoding

### 네트워크 테스트 코드 작성
* [x] 네트워크 관련 객체 테스트 코드 작성

### 서버에 요청
* [x] 메인 화면(해당 도시 숙소 및 필터 조건 설정 후 조건이 적용된 숙소들)
* [x] 필터링 화면 - 가격 (평균 가격, 가격대별 숙소수)
* [x] 즐겨찾기 탭 - 즐겨찾기된 숙소들
* [x] 메인화면 숙소 즐겨찾기 등록/해제 요청
* [x] 필터링 화면 - 가격, 날짜, 인원수
* [x] 즐겨찾기 탭의 숙소 즐겨찾기 해제 요청
* [x] 도시 선택 화면 - 도시 리스트

## 이미지 캐싱
* [ ] 메인 화면 썸네일 숙소 이미지
* [ ] 상세 화면 숙소 이미지
* [ ] 즐겨찾기 탭 썸네일 숙소 이미지

## OAuth 로그인
* [x] OAuth 깃허브 로그인

**Comment by Limwin94** [comment]
### 현재까지 구현이 된 것.
1. 로그인 후 (현재는 OAuth 적용 안하고 있음.) picker에 넣어줄 도시명 리스트를 받아와 picker에 넣어줌.
2. 메인뷰 (숙소 리스트)에는 네트워크 통신 적용하고 있지만, 통신 로직은 구현.
3. 메인뷰의 하위뷰들 (가격, 날짜, 인원 필터링 뷰)에서 설정한 데이터들을 메인뷰로 전달되도록 함.

### 이후 구현할 것.
1. 하위뷰들에서 가져온 데이터들로 메인뷰 숙소 리스트를 받아오기.
2. 가격 필터링 뷰에서 평균 숙박요금 받아와서 적용해주기.
3. 스크롤 시 offset 처리
4. 이미지 캐싱

**Comment by dev-Lena** [comment]
데모 끝! 🥳
고생 많이하셨습니다!!
