### ISSUE TITLE
[iOS - Pair] 0520 메인화면 + 인원수 화면

### ISSUE THREAD

**Issue by Limwin94** [codesquad-member-2020/airbnb-05#8]
### 공통작업
1. CollectionView 이미지 안나오는 부분 각자 수정
2. 수정완료한 사람이 머지 후 코드 설명

### 분업
- 린 : 인원수 설정 뷰 
- 레나 : 메인 화면 전반적인 뷰 구성 및 클래스 연결, 뷰 기능

**Comment by dev-Lena** [comment]
공통작업 1번 : #10 @Limwin94  리뷰 부탁드립니다!
분업 : [iOS] 메인 화면 추가 구성 (검색바, 필터 버튼, 맵 버튼, 슈퍼호스트 라벨) #11

**Comment by dev-Lena** [comment]
분업은 0521에 이어서 하도록 하겠습니다
